import io
from contextlib import redirect_stdout
import json
from pathlib import Path
import subprocess
import tempfile
import unittest

from docsprout import __version__
from docsprout.cli import main
from docsprout.github_pages import (
    CANONICAL_WORKFLOW_RELATIVE_PATH,
    LEGACY_WORKFLOW_RELATIVE_PATH,
    render_workflow,
)


def _legacy_render(version: str) -> str:
    """Reconstruct the pre-rebrand managed workflow for compatibility tests."""
    return (
        render_workflow(version)
        .replace("# DocSprout managed workflow: github-pages v1", "# DocKit managed workflow: github-pages v1")
        .replace("Generated by DocSprout", "Generated by DocKit")
        .replace("docsprout github-pages --update", "dockit-fp github-pages --update")
        .replace("name: DocSprout Pages", "name: DocKit Pages")
        .replace("ikelaiah/docsprout/", "ikelaiah/dockit-fp/")
    )


class GitHubPagesCommandTests(unittest.TestCase):
    def _git(self, root: Path, *arguments: str) -> None:
        subprocess.run(["git", *arguments], cwd=root, check=True, capture_output=True, text=True)

    def _run(self, root: Path, *arguments: str) -> tuple[int, str]:
        output = io.StringIO()
        with redirect_stdout(output):
            result = main(["github-pages", *arguments, "--root", str(root)])
        return result, output.getvalue()

    def test_initialises_a_readme_only_git_repository_and_creates_a_pinned_workflow(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            readme = root / "README.md"
            readme.write_text("# Existing documentation\n", encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(0, result)
            self.assertEqual("# Existing documentation\n", readme.read_text(encoding="utf-8"))
            layout = json.loads((root / "docs" / "layout.json").read_text(encoding="utf-8"))
            self.assertEqual({"path": "README.md", "source": "root"}, layout["home"])
            self.assertTrue((root / "docs" / "docsprout.json").is_file())
            self.assertEqual(
                render_workflow(f"v{__version__}"),
                (root / CANONICAL_WORKFLOW_RELATIVE_PATH).read_text(encoding="utf-8"),
            )
            self.assertIn("DocSprout is ready for GitHub Pages.", output)
            self.assertIn("git add .", output)
            self.assertIn("git push", output)

    def test_preserves_existing_configuration_and_is_idempotent_without_a_remote(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            docs = root / "docs"
            docs.mkdir()
            (docs / "index.md").write_text("# Existing home", encoding="utf-8")
            (docs / "guide.md").write_text("# Existing guide", encoding="utf-8")
            config = docs / "docsprout.json"
            layout = docs / "layout.json"
            config.write_text('{"schema_version": 1, "project": {"name": "Kept"}}\n', encoding="utf-8")
            layout.write_text('{"schema_version": 1, "home": {"path": "guide.md"}, "navigation": [{"title": "Docs", "pages": [{"title": "Home", "path": "index.md"}, {"title": "Guide", "path": "guide.md"}]}]}\n', encoding="utf-8")
            before = {path: path.read_text(encoding="utf-8") for path in (config, layout)}

            self.assertEqual(0, self._run(root)[0])
            workflow = root / CANONICAL_WORKFLOW_RELATIVE_PATH
            configured = {path: path.read_text(encoding="utf-8") for path in (*before, workflow)}
            result, output = self._run(root)

            self.assertEqual(0, result)
            self.assertEqual(before, {path: path.read_text(encoding="utf-8") for path in before})
            self.assertEqual(configured, {path: path.read_text(encoding="utf-8") for path in configured})
            self.assertIn("No changes required.", output)
            self.assertIn("not connected to GitHub yet", output)

    def test_requires_a_git_repository_before_creating_files(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)

            result, output = self._run(root)

            self.assertEqual(1, result)
            self.assertIn("not a Git repository", output)
            self.assertFalse((root / "docs").exists())
            self.assertFalse((root / CANONICAL_WORKFLOW_RELATIVE_PATH).exists())

    def test_requires_explicit_update_for_an_outdated_managed_workflow(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            self.assertEqual(0, self._run(root)[0])
            workflow = root / CANONICAL_WORKFLOW_RELATIVE_PATH
            workflow.write_text(render_workflow("v0.12.1"), encoding="utf-8")
            layout = root / "docs" / "layout.json"
            layout_before = layout.read_text(encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(0, result)
            self.assertEqual(render_workflow("v0.12.1"), workflow.read_text(encoding="utf-8"))
            self.assertEqual(layout_before, layout.read_text(encoding="utf-8"))
            self.assertIn("--update", output)
            result, output = self._run(root, "--update")
            self.assertEqual(0, result)
            self.assertEqual(render_workflow(f"v{__version__}"), workflow.read_text(encoding="utf-8"))
            self.assertEqual(layout_before, layout.read_text(encoding="utf-8"))
            self.assertIn("Updated", output)

    def test_updates_a_recognised_managed_legacy_workflow_without_creating_a_second_one(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            legacy = root / LEGACY_WORKFLOW_RELATIVE_PATH
            legacy.parent.mkdir(parents=True)
            legacy.write_text(_legacy_render("v0.12.1"), encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(0, result)
            self.assertEqual(_legacy_render("v0.12.1"), legacy.read_text(encoding="utf-8"))
            self.assertIn("--update", output)
            self.assertFalse((root / CANONICAL_WORKFLOW_RELATIVE_PATH).exists())

            result, output = self._run(root, "--update")

            self.assertEqual(0, result)
            self.assertEqual(render_workflow(f"v{__version__}"), legacy.read_text(encoding="utf-8"))
            self.assertFalse((root / CANONICAL_WORKFLOW_RELATIVE_PATH).exists())
            self.assertIn("Updated", output)

    def test_refuses_to_overwrite_an_unmanaged_or_malformed_workflow(self) -> None:
        for contents, expected in (("name: Personal Pages\n", "not managed by DocSprout"), ("# DocSprout managed workflow: github-pages v1\nname: Broken\n", "malformed")):
            with self.subTest(expected=expected), tempfile.TemporaryDirectory() as temporary:
                root = Path(temporary)
                self._git(root, "init")
                workflow = root / CANONICAL_WORKFLOW_RELATIVE_PATH
                workflow.parent.mkdir(parents=True)
                workflow.write_text(contents, encoding="utf-8")

                result, output = self._run(root)

                self.assertEqual(1, result)
                self.assertEqual(contents, workflow.read_text(encoding="utf-8"))
                self.assertFalse((root / "docs").exists())
                self.assertIn(expected, output)

    def test_refuses_an_unmanaged_legacy_workflow_instead_of_creating_a_second_one(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            legacy = root / LEGACY_WORKFLOW_RELATIVE_PATH
            legacy.parent.mkdir(parents=True)
            legacy.write_text("name: Personal Pages\n", encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(1, result)
            self.assertIn("not managed by DocSprout", output)
            self.assertFalse((root / CANONICAL_WORKFLOW_RELATIVE_PATH).exists())
            self.assertEqual("name: Personal Pages\n", legacy.read_text(encoding="utf-8"))

    def test_refuses_when_both_managed_workflow_paths_exist(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            canonical = root / CANONICAL_WORKFLOW_RELATIVE_PATH
            legacy = root / LEGACY_WORKFLOW_RELATIVE_PATH
            canonical.parent.mkdir(parents=True)
            canonical.write_text(render_workflow(f"v{__version__}"), encoding="utf-8")
            legacy.write_text(_legacy_render("v0.12.1"), encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(1, result)
            self.assertIn("second deployment workflow", output)
            self.assertEqual(render_workflow(f"v{__version__}"), canonical.read_text(encoding="utf-8"))
            self.assertEqual(_legacy_render("v0.12.1"), legacy.read_text(encoding="utf-8"))

    def test_rejects_invalid_existing_docsprout_configuration_without_repairing_it(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            docs = root / "docs"
            docs.mkdir()
            config = docs / "docsprout.json"
            config.write_text('{"schema_version": 1, "project": {"name": "Broken"}}\n', encoding="utf-8")

            result, output = self._run(root)

            self.assertEqual(1, result)
            self.assertIn("existing DocSprout configuration is invalid", output)
            self.assertFalse((root / CANONICAL_WORKFLOW_RELATIVE_PATH).exists())
            self.assertEqual('{"schema_version": 1, "project": {"name": "Broken"}}\n', config.read_text(encoding="utf-8"))

    def test_doctor_reports_a_current_managed_pages_workflow_and_its_pin(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            self.assertEqual(0, self._run(root)[0])

            output = io.StringIO()
            with redirect_stdout(output):
                self.assertEqual(0, main(["doctor", "--root", str(root)]))

            self.assertIn("GitHub Pages workflow: configured", output.getvalue())
            self.assertIn(f"DocSprout version: v{__version__}", output.getvalue())

    def test_doctor_reports_a_managed_legacy_workflow(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init")
            with redirect_stdout(io.StringIO()):
                self.assertEqual(0, main(["init", "--root", str(root)]))
            legacy = root / LEGACY_WORKFLOW_RELATIVE_PATH
            legacy.parent.mkdir(parents=True)
            legacy.write_text(_legacy_render("v0.12.1"), encoding="utf-8")

            output = io.StringIO()
            with redirect_stdout(output):
                self.assertEqual(0, main(["doctor", "--root", str(root)]))

            self.assertIn("GitHub Pages workflow: update available", output.getvalue())
            self.assertIn("docsprout github-pages --update", output.getvalue())
