name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  documentation:
    uses: ikelaiah/docsprout/.github/workflows/publish-docs.yml@v1.1.5
    with:
      versioned: false
      release: latest
    permissions:
      contents: read
      pages: write
      id-token: write
