"""Deterministic, safely-owned GitHub Pages caller-workflow support."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re


CANONICAL_WORKFLOW_RELATIVE_PATH = Path(".github/workflows/docsprout-pages.yml")
LEGACY_WORKFLOW_RELATIVE_PATH = Path(".github/workflows/dockit-pages.yml")
WORKFLOW_RELATIVE_PATH = CANONICAL_WORKFLOW_RELATIVE_PATH
MANAGED_MARKER = "# DocSprout managed workflow: github-pages v1"
LEGACY_MANAGED_MARKER = "# DocKit managed workflow: github-pages v1"
_MANAGED_MARKERS = (MANAGED_MARKER, LEGACY_MANAGED_MARKER)
_GENERATED_COMMENTS = ("# Generated by DocSprout.", "# Generated by DocKit.")
_PIN = re.compile(
    r"^\s*uses:\s*ikelaiah/(?:docsprout|dockit-fp)/\.github/workflows/publish-docs\.yml@"
    r"(?P<version>v[0-9][0-9A-Za-z._-]*)\s*$",
    re.MULTILINE,
)
_REQUIRED_TEXT = (
    "push:",
    "workflow_dispatch:",
    "github.event.repository.default_branch",
    "versioned: false",
    "release: latest",
    "contents: read",
    "pages: write",
    "id-token: write",
)


@dataclass(frozen=True)
class WorkflowInspection:
    state: str
    version: str | None = None
    path: Path | None = None


def render_workflow(version: str) -> str:
    """Return the complete maintained caller workflow for one DocSprout release."""
    return f"""{MANAGED_MARKER}
# Generated by DocSprout. Update with `docsprout github-pages --update`.
name: DocSprout Pages

on:
  push:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  documentation:
    if: github.ref == format('refs/heads/{{0}}', github.event.repository.default_branch)
    uses: ikelaiah/docsprout/.github/workflows/publish-docs.yml@{version}
    with:
      versioned: false
      release: latest
    permissions:
      contents: read
      pages: write
      id-token: write
"""


def inspect_workflow(path: Path, version: str) -> WorkflowInspection:
    """Classify a workflow at the canonical or the pre-rebrand managed path."""
    # The command's root is resolved first, so these are the only mutable path
    # components between it and the managed filename. Refuse indirection rather
    # than allowing --update to follow a repository-controlled symlink.
    if any(candidate.is_symlink() for candidate in (path.parent.parent, path.parent, path)):
        return WorkflowInspection("unsafe", path=path)
    if not path.exists():
        return WorkflowInspection("absent", path=path)
    text = path.read_text(encoding="utf-8", errors="replace")
    if not any(marker in text for marker in _MANAGED_MARKERS):
        return WorkflowInspection("unmanaged", path=path)
    pin = _PIN.search(text)
    if (
        pin is None
        or not any(comment in text for comment in _GENERATED_COMMENTS)
        or not all(item in text for item in _REQUIRED_TEXT)
    ):
        return WorkflowInspection("malformed", path=path)
    found_version = pin.group("version")
    if text == render_workflow(version):
        return WorkflowInspection("current", found_version, path)
    return WorkflowInspection("outdated", found_version, path)
