"""Safe filesystem primitives for generated documentation output."""

from pathlib import Path
import shutil

from .errors import DocSproutError

OWNERSHIP_MARKER = ".docsprout-site"
LEGACY_OWNERSHIP_MARKER = ".dockit-fp-site"


def _owned_marker(output: Path) -> str | None:
    for marker in (OWNERSHIP_MARKER, LEGACY_OWNERSHIP_MARKER):
        if (output / marker).is_file():
            return marker
    return None


def prepare_output(output: Path) -> None:
    """Empty a DocSprout-owned output directory and recreate its marker.

    Output generated by the pre-rebrand DocKit-FP name is recognised through
    its legacy marker, then replaced with the canonical DocSprout marker.
    """
    output = output.resolve()
    if output.exists():
        if not output.is_dir():
            raise DocSproutError(f"Output path is not a directory: {output}")
        if _owned_marker(output) is None:
            raise DocSproutError(
                f"Refusing to replace output directory {output}: it is not owned by DocSprout "
                f"(missing {OWNERSHIP_MARKER})."
            )
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / OWNERSHIP_MARKER).write_text("DocSprout generated output.\n", encoding="utf-8")
